# Generated by Django 5.2.11 on 2026-02-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cognitive_fingerprint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
