# Generated by Django 5.2.11 on 2026-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_document_cognitive_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='section_fingerprints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tamper_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
