# Generated by Django 5.2.11 on 2026-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_documentpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sha256_hash',
            field=models.CharField(max_length=64),
        ),
    ]
