# Generated by Django 5.2.11 on 2026-02-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='myapp.document'),
        ),
    ]
